// <auto-generated />
using System;
using MarketPlace.Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketPlace.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250824144830_SeedingDataforproduct")]
    partial class SeedingDataforproduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketPlace.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            DatePosted = new DateTime(2025, 8, 24, 14, 48, 29, 733, DateTimeKind.Utc).AddTicks(56),
                            Description = "Powerful laptop with 16GB RAM",
                            ImageUrl = "images/laptop.png",
                            Name = "Laptop",
                            Price = 750.00m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            DatePosted = new DateTime(2025, 8, 24, 14, 48, 29, 733, DateTimeKind.Utc).AddTicks(64),
                            Description = "Calculus textbook for university",
                            ImageUrl = "images/textbook.png",
                            Name = "Textbook",
                            Price = 40.00m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 3,
                            Category = 3,
                            DatePosted = new DateTime(2025, 8, 24, 14, 48, 29, 733, DateTimeKind.Utc).AddTicks(70),
                            Description = "Wireless noise-cancelling headphones",
                            ImageUrl = "images/headphones.png",
                            Name = "Headphones",
                            Price = 120.00m,
                            Status = "Available"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
